// Dependencies
import Head from 'next/head'
import Image from 'next/image'
import Moment from 'react-moment'
import styled from 'styled-components'

// Required Components
import Socials from '../components/Socials'
import Banner from '../components/Banner'

// Utilities Used
import { respondTo } from '../utils/_respondTo'

const Wrapper = styled.div`
	color: ${({ theme }) => theme.colors.secondary};
	display: flex;
	flex-direction: column;
	height: 100vh;
	justify-content: center;
	align-items: center;
`

const Intro = styled.main`
	width: 75%;
	padding: 0;
	margin: 0;
	display: flex;
	flex: auto 1;
	flex-direction: column;
	justify-content: center;
	align-items: start;
	font-size: 1rem;

	${respondTo.lg`
    width: 60%;
  `}
`
const Para = styled.p`
	font-family: 'Noto Sans JP', sans-serif;
	color: ${({ theme }) => theme.colors.primary};
	padding: 0;
	margin: 0;
	text-align: left;
	font-size: 1.15rem;

	${respondTo.sm`
    font-size: 2.25rem;
  `}
`

const Grouped = styled.div`
	color: ${({ theme }) => theme.colors.primary};
	font-weight: bold;
	padding-bottom: 50px;
`

const Footer = styled.section`
	color: ${({ theme }) => theme.colors.onyx};
	font-size: 1rem;
`
const Title = styled.h1`
	font-family: 'Poppins', sans-serif;
	font-size: 2.75em;
	font-weight: 300;
	padding: 0;
	margin: 0.65rem 0 0.65rem;
	color: ${({ theme }) => theme.colors.powderWhite};

	strong {
		font-weight: 600;
	}

	${respondTo.sm`
    font-size: 4.75rem;
  `}
`

export default function Home() {
	return (
		<>
			<Head>
				<title>Caleb White - Frontend Engineer - Portland, OR</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<Wrapper>
				<Banner>New website launching Late May/Early June 2021</Banner>
				<Intro>
					<Title>
						Hey, I'm <strong>Caleb</strong>.
					</Title>
					<Para>I'm a Portland based Frontend Engineer.</Para>
					<Socials />
				</Intro>

				<Footer>
					<p>
						Copyright &copy; <Moment format='YYYY' /> Caleb White.
						All Rights Reserved.
					</p>
				</Footer>
			</Wrapper>
		</>
	)
}
