// Dependencies
import Head from 'next/head'
import Image from 'next/image'
import Moment from 'react-moment'
import styled from 'styled-components'

// Required Components
import Socials from '../components/Socials'

// Utilities Used
import { respondTo } from '../utils/_respondTo'

const Wrapper = styled.div`
	color: ${({ theme }) => theme.colors.secondary};
	display: flex;
	flex-direction: column;
	height: 100vh;
	justify-content: center;
	align-items: center;
`

const Intro = styled.main`
	display: flex;
	flex: auto 1;
	flex-direction: column;
	justify-content: center;
	align-items: center;
	font-size: 0.9rem;

	${respondTo.sm`
    font-size: 1.25rem;
  `}
`
const Para = styled.p`
	color: ${({ theme }) => theme.colors.primary};
	padding: 0;
	margin: 0;
	text-align: center;
`

const Grouped = styled.div`
	color: ${({ theme }) => theme.colors.primary};
	font-weight: bold;
	padding-bottom: 50px;
`

const Footer = styled.section`
	color: ${({ theme }) => theme.colors.onyx};
	font-size: 1rem;
`
const Title = styled.h1`
	font-size: 3.5em;
	padding: 0;
	margin: 0.65rem 0 0.65rem;
	color: ${({ theme }) => theme.colors.powderWhite};
`

export default function Home() {
	return (
		<>
			<Head>
				<title>Caleb White - Frontend Engineer - Portland, OR</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<Wrapper>
				<Intro>
					<Title>Hey, I'm Caleb.</Title>
					<Para>I'm a Frontend Engineer from Portland, OR</Para>

					{/* <Para>
						New website coming very soon! (Late May/Early June 2021)
					</Para> */}
					<Socials />
				</Intro>

				<Footer>
					<p>
						Copyright &copy; <Moment format='YYYY' /> Caleb White.
						All Rights Reserved.
					</p>
				</Footer>
			</Wrapper>
		</>
	)
}
