/* eslint-disable react/no-unescaped-entities */

// Dependencies
import React from 'react'
import Head from 'next/head'
import Moment from 'react-moment'
import styled from 'styled-components'

// Required Components
import Socials from '../components/Socials'
import Banner from '../components/Banner'
import ContentWrapper from '../components/ContentWrapper'
import Navigation from '../components/Navigation'

// Utilities Used
import { respondTo } from '../utils/_respondTo'

const Intro = styled.main`
	width: 75%;
	height: 100vh;
	padding: 0;
	margin: 0;
	display: flex;
	flex: auto 1;
	flex-direction: column;
	justify-content: center;
	align-items: start;
	font-size: ${({ theme }) => theme.fontSizes.sm};

	${respondTo.lg`
    width: 60%;
  `}
`
const Para = styled.p`
	font-family: 'Noto Sans JP', sans-serif;
	color: ${({ theme }) => theme.colors.wolfGray};
	padding: 30px 0;
	margin: 0;
	text-align: left;
	font-size: ${({ theme }) => theme.fontSizes.md};
	line-height: 1.5;

	a {
		display: inline-block;
		line-height: 0.8;
		color: ${({ theme }) => theme.colors.powderWhite};
		font-weight: 500;
		border-bottom: 4px solid ${({ theme }) => theme.colors.primary};
		text-decoration: none;
	}

	a:hover {
		color: ${({ theme }) => theme.colors.primary};
		transition: 0.15s ease-in-out;
		border: none;
	}
`

const Footer = styled.section`
	color: ${({ theme }) => theme.colors.onyx};
	font-size: 1rem;
`
const SiteTitle = styled.h1`
	font-family: 'Poppins', sans-serif;
	font-size: ${({ theme }) => theme.fontSizes.xl};
	font-weight: 300;
	padding: 0;
	margin: 0.65rem 0 0.65rem;
	color: ${({ theme }) => theme.colors.powderWhite};

	strong {
		font-weight: 600;
	}

	${respondTo.sm`
    font-size: 4.75rem;
  `}
`

export default function Home() {
	return (
		<>
			<Head>
				<title>Caleb White - Frontend Engineer - Portland, OR</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<ContentWrapper>
				<Navigation />
				<Intro>
					<SiteTitle>
						Hey, I'm <strong>Caleb</strong>
					</SiteTitle>
					<h2>I'm a Portland, OR based Frontend Engineer.</h2>
					<Para>
						I'm passionate about building a better web with
						exceptional digital experiences. Currently freelancing
						as{' '}
						<a href='https://www.fairwaycreative.com'>
							Fairway Creative
						</a>{' '}
						and open to full-time remote opportunities. You can
						learn more about my current skills, view cv, and more
						below.
					</Para>
					<Socials />
				</Intro>

				<Footer>
					<p>
						Copyright &copy; <Moment format='YYYY' /> Caleb White.
						All Rights Reserved.
					</p>
				</Footer>
			</ContentWrapper>
		</>
	)
}
